### ISSUE TITLE
Add variant length/end coordinate field

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/bio2zarr#278]
To implement range queries in the same way that htslib does, we need to define what the end coordinate is. The best way to do this is to define an array that we store with this value.

Following the general rule of thumb, we should do whatever htslib does in order to compute this value so that we can guarantee compatibility.

Refs:
- Cyvcf2 has an [end](https://brentp.github.io/cyvcf2/docstrings.html#cyvcf2.cyvcf2.Variant.end) attribute (which is hopefully what we want)
- The VCF spec defines an INFO/END key: [section 1.4.1](https://samtools.github.io/hts-specs/VCFv4.2.pdf). "For precise variants, END is POS + length of REF allele - 1, and the for imprecise variants the corresponding best estimate"

Figuring out what htslib does will take a little digging, but a reasonable approach would seem to be to use the ``END`` value if it exists, and POS + length of REF allele - 1 otherwise?

**Comment by tomwhite** [comment]
I agree this is tricky to get right!

> * Cyvcf2 has an [end](https://brentp.github.io/cyvcf2/docstrings.html#cyvcf2.cyvcf2.Variant.end) attribute (which is hopefully what we want)

It's just [getting the `rlen` field from htslib](https://github.com/brentp/cyvcf2/blob/86248965fd6f8724403c756bc8b606a48b76b29f/cyvcf2/cyvcf2.pyx#L2039), so it looks OK.

Slightly confusingly, `INFO/END` is deprecated in [VCF 4.5](https://samtools.github.io/hts-specs/VCFv4.5.pdf). However, it is still defined as a computed value, so that doesn't really change anything (I think):

> The computed value of this field is used to compute BCF’s `rlen` field (see 6.3.1) and is important when indexing
VCF/BCF files to enable random access and querying by position.

Another thing I wonder: if we store length then we are not making any comment on the coordinate system (open or closed intervals), which might make adding it to the spec easier (and easier to support PLINK and BGEN).
